# -*- coding: utf-8 -*-
"""EdVision_data_cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q8e5fhvNDq31knol31_b22niEIEdNdpA
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
qs = pd.read_csv('/content/drive/My Drive/qs-world-rankings-2025.csv')
the = pd.read_csv('/content/drive/My Drive/THE World University Rankings 2016-2026.csv')

print(qs.head())
qs.info()
qs.describe()

print(the.head())
the.info()
the.describe()

qs = qs.drop_duplicates()
the = the.drop_duplicates()

qs.isnull().sum()
the.isnull().sum()

qs['Institution Name'] = qs['Institution Name'].str.strip().str.lower()
the['Name'] = the['Name'].str.strip().str.lower()
qs['Location'] = qs['Location'].str.strip().str.lower()
the['Country'] = the['Country'].str.strip().str.lower()

merged = pd.merge(qs, the, left_on=['Institution Name', 'Location'], right_on=['Name', 'Country'], how='outer')

merged.to_csv('/content/drive/MyDrive/university_cleaned.csv', index=False)

df = pd.read_csv('/content/drive/MyDrive/university_cleaned.csv')

# Clean 'Student Population' (from THE rankings in df) and 'International Students_y' (from THE rankings in df)
def clean_population_range(s):
    if pd.isna(s):
        return None
    s = str(s).replace(',', '').strip().lower()
    if s == 'n/a':
        return None
    if '-' in s:
        parts = s.split('-')
        try:
            return (float(parts[0]) + float(parts[1])) / 2
        except ValueError:
            return None
    elif '+' in s:
        try:
            return float(s.replace('+', ''))
        except ValueError:
            return None
    elif '~' in s:
        try:
            return float(s.replace('~', ''))
        except ValueError:
            return None
    try:
        return float(s)
    except ValueError:
        return None

def clean_percentage_range(s):
    if pd.isna(s):
        return None
    s = str(s).replace('%', '').strip().lower()
    if s == 'n/a':
        return None
    if '-' in s:
        parts = s.split('-')
        try:
            return (float(parts[0]) + float(parts[1])) / 2
        except ValueError:
            return None
    try:
        return float(s)
    except ValueError:
        return None

df['Student_Population_Cleaned'] = df['Student Population'].apply(clean_population_range)
df['International_Students_y_Cleaned'] = df['International Students_y'].apply(clean_percentage_range)

df['Global_Rank_Score'] = 100 - df['Rank']   # Using 'Rank' from THE
df['Research_Productivity_Index'] = df['Research Quality'] / df['Students to Staff Ratio']
df['Faculty_Student_Ratio'] = df['Faculty Student']
df['Intl_Student_Percentage'] = df['International_Students_y_Cleaned']

df[['Student_Population_Cleaned','International_Students_y_Cleaned','Global_Rank_Score','Research_Productivity_Index']].describe()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['Global_Rank_Score','Research_Productivity_Index','Intl_Student_Percentage']] = scaler.fit_transform(
    df[['Global_Rank_Score','Research_Productivity_Index','Intl_Student_Percentage']]
)

df['Performance_Index'] = (
    0.4*df['Global_Rank_Score'] +
    0.3*df['Research_Productivity_Index'] +
    0.3*df['Intl_Student_Percentage']
)

import plotly.express as px
df['Performance_Index'] = (
    0.4*df['Global_Rank_Score'] +
    0.3*df['Research_Productivity_Index'] +
    0.3*df['Intl_Student_Percentage']
)

print(df.columns)

fig = px.bar(
    df.sort_values('Performance_Index', ascending=False).head(10),
    x='Institution Name',   # <-- replace with the exact column name in your df
    y='Performance_Index',
    title='Top 10 Universities by Performance Index'
)

fig.show()